// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: runtime/runtime.proto

package runtime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRuntime_Run_FullMethodName = "/runtime.AgentRuntime/Run"
)

// AgentRuntimeClient is the client API for AgentRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentRuntimeClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
}

type agentRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRuntimeClient(cc grpc.ClientConnInterface) AgentRuntimeClient {
	return &agentRuntimeClient{cc}
}

func (c *agentRuntimeClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentRuntimeServer is the server API for AgentRuntime service.
// All implementations must embed UnimplementedAgentRuntimeServer
// for forward compatibility.
type AgentRuntimeServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	mustEmbedUnimplementedAgentRuntimeServer()
}

// UnimplementedAgentRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRuntimeServer struct{}

func (UnimplementedAgentRuntimeServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedAgentRuntimeServer) mustEmbedUnimplementedAgentRuntimeServer() {}
func (UnimplementedAgentRuntimeServer) testEmbeddedByValue()                      {}

// UnsafeAgentRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRuntimeServer will
// result in compilation errors.
type UnsafeAgentRuntimeServer interface {
	mustEmbedUnimplementedAgentRuntimeServer()
}

func RegisterAgentRuntimeServer(s grpc.ServiceRegistrar, srv AgentRuntimeServer) {
	// If the following call pancis, it indicates UnimplementedAgentRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRuntime_ServiceDesc, srv)
}

func _AgentRuntime_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentRuntime_ServiceDesc is the grpc.ServiceDesc for AgentRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.AgentRuntime",
	HandlerType: (*AgentRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _AgentRuntime_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime/runtime.proto",
}
